# Generated by Django 4.2.23 on 2025-06-14 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0003_participante_externo_id_prova_externo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraGabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('leitura_respostas', models.TextField(help_text='String retornada pela leitura automática')),
                ('erro', models.IntegerField(choices=[(0, 'Nenhum'), (1, 'Erro Aztec'), (2, 'Imprecisão'), (3, 'Erro fatal')])),
                ('nota', models.FloatField(blank=True, null=True)),
                ('acertos', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('caminho_imagem', models.CharField(max_length=500)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.participante')),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.prova')),
            ],
        ),
    ]
