# Generated by Django 4.2.23 on 2025-06-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leituragabarito',
            name='externo_participante_id',
            field=models.BigIntegerField(blank=True, help_text='ID do participante retornado pelo scanner', null=True),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='externo_prova_id',
            field=models.BigIntegerField(blank=True, help_text='ID da prova retornado pelo scanner', null=True),
        ),
    ]
