# Generated by Django 4.2.23 on 2025-06-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_leituragabarito_externo_participante_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leituragabarito',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='escola_aluno',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='fase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='nome_aluno',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leituragabarito',
            name='numero_inscricao',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituragabarito',
            name='externo_participante_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituragabarito',
            name='externo_prova_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituragabarito',
            name='leitura_respostas',
            field=models.TextField(),
        ),
    ]
