# Generated by Django 4.2.23 on 2025-06-12 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('numero_questoes', models.PositiveIntegerField()),
                ('respostas_corretas', models.TextField(help_text="ex: 'ABCDA...'")),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.escola')),
            ],
        ),
        migrations.CreateModel(
            name='PesoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_questao', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='registro.prova')),
            ],
            options={
                'unique_together': {('prova', 'numero_questao')},
            },
        ),
    ]
