# Generated by Django 4.2.23 on 2025-06-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pesoquestao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pesoquestao',
            name='prova',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='data',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='prova',
            name='numero_questoes',
        ),
        migrations.AlterField(
            model_name='participante',
            name='escola',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='prova',
            name='respostas_corretas',
            field=models.TextField(help_text="String ex: 'ABCDA...'"),
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
        migrations.DeleteModel(
            name='PesoQuestao',
        ),
    ]
