# Generated by Django 4.2.23 on 2025-06-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_pesoquestao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='externo_id',
            field=models.BigIntegerField(blank=True, help_text='ID externo usado pelo leitor de gabaritos', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='externo_id',
            field=models.BigIntegerField(blank=True, help_text='ID externo da prova (do scanner)', null=True, unique=True),
        ),
    ]
