# Generated by Django 4.2.23 on 2025-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_participante_externo_id_prova_externo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='escola',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
